### ISSUE TITLE
TOTK: Minigames always showing

### ISSUE THREAD

**Issue by JohnVeness** [zeldadungeon/maps#121]
For some reason, minigames in the TOTK map are always showing for me, even if the marker is turned off, or even if all markers are turned off.

**Comment by KPJoshi** [comment]
Also, they do not get highlighted when you turn all markers except minigames off. They also do not seem to be in the locations.json files?

**Comment by Thortok** [comment]
In addition, you cannot override them to show at greater zoom levels like you can with other pin types

**Comment by ARandomGitHubUser1** [comment]
Fixed

**Comment by Thortok** [comment]
Not fixed by disabling the pin so that they never show

**Comment by ARandomGitHubUser1** [comment]
It made the wiki consistent with the code so that it _could_ be disabled, not breaking it to never show. It fixed the issue for me, at least.
In any case, #149 fixes it as well, so once/if that's merged that also fixes it.

**Comment by Thortok** [comment]
I tested it and I could not get the minigame icons to show at any zoom level, they were completely disabled like the pin type had no data at all. That's why I reverted that edit.

**Comment by LockeExile** [comment]
fixed by #149
