### ISSUE TITLE
Show marker for current location

### ISSUE THREAD

**Issue by sanityormadness** [zeldadungeon/maps#127]
If you click a link to the map - e.g., https://www.zeldadungeon.net/tears-of-the-kingdom-interactive-map/?lng=-0757&lat=3535&l=Surface (which is a non-scaling Strong Zonaite Sword, for the record), there is no marker for this unless it is something explicitly marked on the map. There should be a "You Are Here"-type marker for any arbitrary location a link brings you to.

**Comment by Thortok** [comment]
Very similar in concept to the idea I had here: https://github.com/zeldadungeon/maps/issues/91

**Comment by LockeExile** [comment]
dupe of #91
