### ISSUE TITLE
Possibility to filter variants?

### ISSUE THREAD

**Issue by JohnVeness** [zeldadungeon/maps#130]
Sometimes I am looking for a specific type of monster, e.g. a Black Hinox because apparently they are more likely to drop guts. At the moment, the Filter tab will show all Hinox and I have to click on each one to find which are Black. Alternatively, I can go into the Search tab and type in black hinox, which will give me a list, but I have to click on each one in the search results for it to show on the map!

It would be great if there was a way to show just (e.g.) Black Hinox on the map. I'm not sure how the UI would look on this - maybe a further level of hierarchy (expandable sections/arrows) in the filter tab, although that might be a bit messy.

**Comment by LockeExile** [comment]
Compendium tab now covers this
