### ISSUE TITLE
Malanya Spring lacks text from wiki page

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#131]
https://www.zeldadungeon.net/maps-beta/totk/?z=5&x=3102&y=4470&l=Surface&m=MaronSpring

![image](https://github.com/zeldadungeon/maps/assets/14281289/12173aac-2274-49c6-9443-93214ef8566c)

**Comment by JohnVeness** [comment]
Probably related, hovering over the edit button shows a link to https://www.zeldadungeon.net/Malanya%20Spring rather than to https://www.zeldadungeon.net/wiki/index.php?action=edit&title=etc. as expected.

It seems the Great Fairies are similarly affected.

**Comment by JohnVeness** [comment]
Is it because public/totk/markers/surface/locations.json doesn't have either source=summary or source=mapns for the Great Fairy/Malanya Spring section?
