### ISSUE TITLE
Possibly misnamed item

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#145]
![image](https://github.com/zeldadungeon/maps/assets/14281289/b60d533c-0c28-4056-bc5a-c48077bd7a45)
![image](https://github.com/zeldadungeon/maps/assets/14281289/0978a025-1051-435b-ad46-b9a46440d1dd)

**Comment by sanityormadness** [comment]
Okay, did a quick check there. SHIELDS fused to wings are "Wing Shield", but WEAPONS (one-handed, two-handed or spear) fused to wings are "Soaring [x]". It's just misnamed.

[Objmap lists it as "Giant Boomerang, Wing" (Which is, honestly, a clearer way to do it): https://objmap-totk.zeldamods.org/#/map/z8,4673.25,3742.625,Surface?id=MainField,J-8,0x8c62ebbd41381d95 ]
