### ISSUE TITLE
Disable edit button?

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#150]
The map has now been completely reviewed and every pin verified and its popup reviewed. For the most part they no longer need revision.

All that remains is to do the bosses (if those popups become editable) and/or any future pin types. But the current pin types (koroks and treasure chests) are pretty much done.

Those with know-how would still be able to edit the popups manually by going to the correct URL. But turning off the edit button would prevent the average user from making unnecessary edits that constantly require reverting.

**Comment by Thortok** [comment]
Can probably also disable the contribute pin as well.

**Comment by JohnVeness** [comment]
Hmm, I'm not sure about this. One of the great advantages of this map over others is its wiki-type nature, and making that less discoverable would reduce people contributing, I think.

**Comment by Thortok** [comment]
The map still links to the wiki and the wiki is still editable.

But the need to go from the map to an edit page without even viewing the page that you're about to edit first, is no longer needed.

Also, the pop-ups are the main thing that is finalized. Reducing people contributing is the goal because there are no more contributions necessary and thus every contribution attempted is actually a negative. Editing would still be possible in the event that a positive contribution is actually needed, but it stops the barrage of bad contributions.
