### ISSUE TITLE
Request - Error message display

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#36]
Given that incorrectly entered data can result in the entire page's worth of pins not loading, and as we begin to clear out user-created pins and convert them to real pins, it's sometimes not immediately obvious when a failure to load has occurred.

Would it be possible to create an error message when the map loads, perhaps small and unobtrusive in the bottom left corner, that indicates which page(s) (from among those it currently expects pin information from) failed to load even a single pin for the map? That can help quickly identify if/when some pins aren't loading as well as speed resolution.

**Comment by LockeExile** [comment]
Implemented by b52c5aee4f6a6a4eded6cb4933316cf2401d7df3
