### ISSUE TITLE
Request - Save currently selected filters even when refreshing

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#52]
If I select multiple filters but then refresh the map, it removes the filters I had selected. Would prefer that they stay remembered.

**Comment by LockeExile** [comment]
can store this in localstorage along with the settings selections

**Comment by Thortok** [comment]
With the sensor+ part added this becomes even more desired - if I select like 7 different specific things based on what I need to upgrade with for instance, then refresh to check pin editing, all my selections are gone

**Comment by LockeExile** [comment]
fixed by c64f3ff702951975bef0b56f897b787886c67f61
(deployed only to beta for now)

**Comment by Thortok** [comment]
I'm back from playing Diablo 4, ready to work on the map again, not sure why but after a few refreshes (perhaps when the map pin data has changed?) it's forgetting my filters again and showing things I had turned off.

**Comment by Thortok** [comment]
Figured it out, when the URL contains a map ID then it ignores/forgets filters, if I shift the map off the pin and then refresh again my filters are back.
