### ISSUE TITLE
IDs for Chests

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#55]
There are some chests in the world that need a bit of explanation of how to unlock or reach.

I would like chests to have IDs so that the map popup for them can be edited in a similar fashion to Koroks, Shrines, and others.

This should combine with my next suggestion: A 'fallback' description if the map popup is blank or not created yet. (Creating a 2nd issue for this suggestion.)

**Comment by LockeExile** [comment]
clarification: chests do have IDs, just need to update infosource. but yeah will take this in combination with fallback #56

**Comment by LockeExile** [comment]
fixed by 6b05df2eab018c47f7f34a2195fa2000bd2a8436
