### ISSUE TITLE
Fallback description if popup text does not exist for ID

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#56]
Although we want the _option_ to be able to create specific popup text for each pin, if that does not yet exist or if there is not a need to create specific text for it (like will be the case with most chests and a lot of other types of pins) then the map should 'fall back' to the previous method of referring to the wiki page that the pin is linking to.

**Comment by LockeExile** [comment]
fixed by 6b05df2eab018c47f7f34a2195fa2000bd2a8436

note this causes the edit link to go to the special map page, even if the content was loaded from the summary page.
