### ISSUE TITLE
Order of recipe food buffs

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#62]
Food:
Full recovery + yellow heart
Stamina wheel (green)
Stamina wheel (yellow+)
heat resist
cold resist
attack up
hot weather attack
cold weather attack
stormy weather attack
defense up
speed up
stealth up
glow
buffless

Will update as I acquire more

**Comment by Thortok** [comment]
added green/yellow stamina and defense up

**Comment by LockeExile** [comment]
Got it:

Max Health Up
Gloom Recovery
Gloom Resistance
Stamina Recovery
Max Stamina Up
Flame Guard
Heat Resistance
Cold Resistance
Shock Resistance
Attack Up
Hot Weather Attack
Cold Weather Attack
Stormy Weather Attack
Defense Up
Speed Up
Swim Speed Up
Slip Resistance
Stealth Up
Glow
