### ISSUE TITLE
Turn off contribution mode

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#66]
A user has suggested (on the wiki talk page) that the pin you get to identify coords be toggled off for those who do not wish to contribute at all.

If such a mode is added I would suggest adding to the tooltip "Contribution mode can be toggled off in settings."

**Comment by slaurent22** [comment]
I can do this

**Comment by slaurent22** [comment]
https://github.com/zeldadungeon/maps/pull/94
