### ISSUE TITLE
Allow editing of popup of caves similar to chests.

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#68]
Created https://www.zeldadungeon.net/wiki/Map:Tears_of_the_Kingdom/Cave_Tabantha_0002 but it does not reflect in the popup for https://www.zeldadungeon.net/tears-of-the-kingdom-interactive-map/?l=Surface&z=4&x=449&y=-3466&m=Cave_Tabantha_0002

Would also be handy if the edit button went there as well instead of the wiki page. (Can always click the name to go to the wiki page instead for editing that.)

**Comment by slaurent22** [comment]
I can do this

**Comment by slaurent22** [comment]
https://github.com/zeldadungeon/maps/pull/95

**Comment by slaurent22** [comment]
redid at https://github.com/zeldadungeon/maps/pull/104
