### ISSUE TITLE
Option to move sidebar menu to the right side

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#80]
The whole thing, buttons and all.

I play with the game on the left and the map on the right, and having the sidebar 'between' game and map is uncomfortable. Also remember this setting so it isn't lost when I refresh.

Thanks!

**Comment by slaurent22** [comment]
I have this implemented locally but it's branched off https://github.com/zeldadungeon/maps/pull/94 - after that merges I'll open a PR for this
