### ISSUE TITLE
No Bubbelfrogs

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#82]
When I filter for Bubblefrogs I see no pins on the map

May be worthwhile to check for any other filters that return zero pins

**Comment by LockeExile** [comment]
oh yeah I think the special horses are broken too

**Comment by slaurent22** [comment]
Quick script shows the following have zero entries in any of the materials.json files:

```
Hylian Pine Cone
Giant Horse
White Horse
Giant White Stallion
Stalhorse
Dondon
Bubbulfrog
```

Furthermore, the `Golden Horse` marker is set to the stable where you receive the side quest, not to the spawn point of the horse.

**Comment by Thortok** [comment]
![image](https://github.com/zeldadungeon/maps/assets/14281289/3bff5df2-b195-4763-aba6-1a4c6dbf82f7)
![image](https://github.com/zeldadungeon/maps/assets/14281289/35426beb-e846-4af1-817a-19729ae936a7)
