### ISSUE TITLE
Missing from Sensor filter:

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#86]
Fire-Breath Lizalfos Horn (or the Fire-Breath Lizalfos you can kill to get them)
Moblin Guts
Dragon scales
Electric Keese Wing

**Comment by LockeExile** [comment]
Those items aren't found lying around by themselves. I added enemies so users can now search for moblins, etc. Dragons are not added yet since they move. I'll create a separate issue for adding dragon paths as a togglable layer.
