### ISSUE TITLE
Allow popups for more pin types

### ISSUE THREAD

**Issue by Thortok** [zeldadungeon/maps#90]
Like with chests, the popups would default to wiki page but allow the user to create a custom popup when needed.

Caves and chasms sometimes need a little additional explanation of how to actually reach them.

**Comment by slaurent22** [comment]
This is basically the same as https://github.com/zeldadungeon/maps/issues/68 right?

**Comment by Thortok** [comment]
As long as it's caves _and_ chasms, think I only asked for caves before

**Comment by slaurent22** [comment]
updated https://github.com/zeldadungeon/maps/pull/104 to include both caves and chasms

**Comment by Thortok** [comment]
Oh and I forgot. Towers, too. Some of them have a slight puzzle to complete first and would be good to be able to put the solution in their popup.

Please make sure the 'Edit' button goes to the popup and not to the main article once this is implemented.

And as before if one doesn't exist (or has been blanked out) then default to the regular info.

**Comment by slaurent22** [comment]
If I don't get to this by the time my PR gets merged, it'll automatically close this issue. So it might go through without towers

**Comment by Thortok** [comment]
The edit button still seems to go to the wiki page instead of to creating a popup page like with chests/seeds/shrines

**Comment by slaurent22** [comment]
> The edit button still seems to go to the wiki page instead of to creating a popup page like with chests/seeds/shrines

I had to open the developer tools (f12), switch to Network, check Disable Cache, then refresh

**Comment by Thortok** [comment]
I did ctrl-F5, that worked, thanks
